# -*- coding: utf-8 -*-
"""Rustatio 界面汉化脚本:对 ui/src 下的 Svelte/JS 做精确字符串替换。"""
import re
import io
import pathlib

TEXTS = {
    'Apply': '应用', 'Settings': '设置', 'Theme': '主题',
    'Uploaded': '已上传', 'Downloaded': '已下载',
    'Total Uploaded': '总上传量', 'Total Downloaded': '总下载量',
    'Ratio': '比率', 'Total Size': '总大小', 'Running': '运行中',
    'Start All': '全部开始', 'Stop All': '全部停止', 'Pause All': '全部暂停',
    'Resume All': '全部恢复', 'New Instance': '新建实例',
    'Live Rates': '实时速率', 'Instances': '实例', 'Downloading': '下载中',
    'States': '状态', 'View': '视图', 'Standard': '标准', 'Grid': '网格', 'Watch': '监视',
    'Loading Rustatio...': '正在加载 Rustatio...',
    'Size': '大小', 'Files': '文件', 'Pieces': '块数', 'Piece Size': '块大小',
    'Select client...': '选择客户端...', 'Select version...': '选择版本...',
    'Start': '开始', 'Target': '目标', 'Duration': '持续时间', 'hrs': '小时',
    'Variance': '波动幅度', 'Filters': '筛选', 'Status': '状态',
    'Tags': '标签', 'Trackers': 'Tracker',
    'No tags found.': '未找到标签。', 'No trackers found.': '未找到 Tracker。',
    'Override': '覆盖', 'Preset': '预设方案', 'No preset': '无预设',
    'Completion': '完成度', 'Already Uploaded': '已上传量',
    'Randomization': '随机化', 'Progressive Rates': '渐变速率',
    'Type': '类型', 'Version': '版本', 'Port': '端口', 'Client': '客户端',
    'VPN sync': 'VPN 同步', 'Custom': '自定义', 'Completion %': '完成度 %',
    'Auto-start after import': '导入后自动开始',
    'Import Torrents': '导入种子', 'Folder Path': '文件夹路径', 'Mode': '模式',
    'Select All': '全选', 'Deselect All': '取消全选', 'Invert Selection': '反选',
    'All Running': '全部运行中', 'All Stopped': '全部已停止', 'All Paused': '全部已暂停',
    'By Tag': '按标签', 'No instances found': '未找到实例',
    'Import': '导入', 'Edit': '编辑',
    'Current tags': '当前标签', 'Add tag...': '添加标签...',
    'Delete Instance': '删除实例',
    'Error': '错误', 'Checking...': '检测中...',
    'IP hidden': 'IP 已隐藏', 'No VPN configured': '未配置 VPN', 'No VPN': '无 VPN',
    'Forwarded port': '转发端口', 'Listening': '监听中',
    'Presets and configuration': '预设与配置',
    'Configure general application settings.': '配置应用常规设置。',
    'Log Level': '日志级别', 'Level': '级别',
    'Warning': '警告', 'Info': '信息', 'Debug': '调试', 'Trace': '跟踪',
    'Window Behavior': '窗口行为', 'On Close': '关闭时',
    'Ask every time': '每次询问', 'Minimize to tray': '最小化到托盘',
    'Quit application': '退出程序',
    'Ask every time:': '每次询问:', 'Minimize to tray:': '最小化到托盘:',
    'Quit application:': '退出程序:',
    'Choose your preferred color theme.': '选择喜欢的配色主题。',
    'Set Default': '设为默认', 'Save Current as Preset': '保存当前为预设',
    'Export Current Config': '导出当前配置', 'Import Preset File': '导入预设文件',
    'Save Preset': '保存预设', 'Export Preset': '导出预设',
    'Progressive': '渐变',
    'Idle: No Leechers': '空闲:无下载者', 'Idle: No Seeders': '空闲:无做种者',
    'Target Ratio': '目标比率', 'Max Upload': '最大上传', 'Max Download': '最大下载',
    'Seed Time': '做种时长', 'When conditions are met': '条件满足时',
    'Delete instance': '删除实例', 'disabled': '已禁用', 'Stop': '停止',
    'Modern BitTorrent Ratio Faker': '现代 BitTorrent 比率管理工具',
    'Authentication Required': '需要身份验证',
    'Enter your API token to continue': '输入 API 令牌以继续',
    'Running in self-hosted server mode': '正在自托管服务器模式运行',
    'Remember my choice': '记住我的选择',
    'View on GitHub': '在 GitHub 上查看',
    'No logs yet': '暂无日志',
    'Application events will appear here': '应用事件将显示在这里',
    'Solution 2:': '方案 2:', 'Example Worker URL:': 'Worker URL 示例:',
    'Update Available': '有可用更新', 'Later': '稍后',
    'Checking for updates...': '正在检查更新...',
    'Browse Server Folders': '浏览服务器文件夹',
    'No VPN configured.': '未配置 VPN。',
    'Gluetun status is unavailable.': 'Gluetun 状态不可用。',
    'VPN sync is disabled on the server.': '服务器已禁用 VPN 同步。',
    'No peer data': '无 peer 数据', 'S/L Ratio:': '做/下比:',
    'Seeders': '做种数', 'Leechers': '下载者数',
    'Upload': '上传', 'Download': '下载',
    'Torrent Download': '种子下载进度',
    'Cumulative Ratio': '累计比率',
    'Watch Explorer': '监视浏览器', 'Visible selection only': '仅可见选择',
    'Watch Directory': '监视目录', 'Max depth': '最大深度',
    'Overview': '概览', 'Folders': '文件夹', 'Loaded': '已加载',
    'Total on disk': '磁盘总计', 'Expand': '展开', 'Collapse': '折叠',
    'Select visible': '选择可见', 'Actions': '操作', 'Folder': '文件夹',
    'Pause': '暂停', 'Resume': '恢复', 'Update': '更新',
}

ATTRS = {
    'Close dialog': '关闭对话框', 'Close sidebar': '收起侧边栏',
    'Close instance': '关闭实例', 'Force delete instance': '强制删除实例',
    'Force delete (file may be missing)': '强制删除(文件可能已丢失)',
    'Force Delete Instance': '强制删除实例',
    'Session uploaded': '本次会话上传', 'Session downloaded': '本次会话下载',
    'Upload speed': '上传速度', 'Total upload rate': '总上传速率',
    'Total download rate': '总下载速率',
    'Start all instances': '启动所有实例', 'Stop all instances': '停止所有实例',
    'Pause all running instances': '暂停所有运行中的实例',
    'Resume all paused instances': '恢复所有已暂停的实例',
    'Add new instance': '添加新实例', 'Current ratio': '当前比率',
    'From watch folder': '来自监视文件夹',
    'View Rustatio on GitHub': '在 GitHub 上查看 Rustatio',
    'Standard view - manage individual instances': '标准视图 - 逐个管理实例',
    'Grid view - manage many instances at once': '网格视图 - 批量管理实例',
    'Watch folder - manage watch files': '监视文件夹 - 管理监视文件',
    'Toggle theme menu': '切换主题菜单', 'Toggle menu': '切换菜单',
    'Click to clear default': '点击清除默认',
    'Set as default for new instances': '设为新实例默认',
    'e.g., My Tracker Config': '例如:我的 Tracker 配置',
    'Describe what this preset is for...': '描述这个预设的用途...',
    'Start faking': '开始伪造', 'Pause faking': '暂停伪造',
    'Resume faking': '恢复伪造', 'Update stats': '更新统计',
    'Stop faking': '停止伪造',
    'Reset zoom to show all data': '重置缩放以显示全部数据',
    'Delete preset': '删除预设',
    'Open filters': '打开筛选',
    'Start selected': '启动选中', 'Stop selected': '停止选中',
    'Pause selected': '暂停选中', 'Resume selected': '恢复选中',
    'Edit selected': '编辑选中', 'Delete selected': '删除选中',
    'Search by name, hash, or tag...': '按名称/哈希/标签搜索...',
    'Search tags...': '搜索标签...', 'Search trackers...': '搜索 Tracker...',
    'Manage tags': '管理标签', 'Add tag...': '添加标签...',
    'Close': '关闭',
    'Override client settings': '覆盖客户端设置',
    'Override transfer rates': '覆盖传输速率',
    'Override initial state': '覆盖初始状态',
    'Override timing': '覆盖时间设置',
    'Override randomization': '覆盖随机化',
    'Override progressive rates': '覆盖渐变速率',
    'Override stop conditions': '覆盖停止条件',
    'Drop zone for torrent files': '种子文件拖放区',
    'Select a folder from your computer': '从电脑选择文件夹',
    'Select visible files': '选择可见文件', 'Select file': '选择文件',
    'Network status unavailable in this mode': '此模式下网络状态不可用',
    'Click to retry': '点击重试', 'Refresh network status': '刷新网络状态',
    'Loaded files': '已加载文件', 'Pending files': '待处理文件',
    'Invalid files': '无效文件', 'Total files on disk': '磁盘上文件总数',
    'Reload selected files': '重新加载选中文件',
    'Delete selected files': '删除选中文件',
    'Clear selected files': '清除选中文件',
    'Choose folder': '选择文件夹', 'Name or path': '名称或路径',
    'Select files in this folder (visible only)': '选择此文件夹中的文件(仅可见项)',
    'Select folder files': '选择文件夹文件',
    'Delete all files in this folder': '删除此文件夹中的全部文件',
    'Reload file': '重新加载文件', 'Delete file': '删除文件',
    'Go to parent directory': '转到上级目录',
    'Show download options': '显示下载选项',
    'Enter your API token': '输入 API 令牌',
    'Dismiss': '关闭',
    'Only works when completion < 100%': '仅在完成度 < 100% 时有效',
    'Close grid mobile panel': '关闭网格移动面板',
}

MSG = {
    'Ready to start faking': '准备开始伪造',
    'Actively faking ratio...': '正在伪造比率...',
    'Select a torrent file to begin': '请选择种子文件以开始',
    'Loading torrent...': '正在加载种子...',
    'Torrent loaded successfully': '种子加载成功',
    'Stopped automatically - condition met': '已自动停止 - 条件满足',
    'Error: ': '错误: ',
    'Please select a torrent file first': '请先选择种子文件',
    'Starting ratio faker...': '正在启动比率伪造...',
    'Failed to start: ': '启动失败: ',
    'Stopping faker...': '正在停止伪造...',
    'Stopped successfully - Stats available for review': '已成功停止 - 可查看统计',
    'Ready to start a new session': '可以开始新会话',
    'Failed to stop: ': '停止失败: ',
    'Failed to pause: ': '暂停失败: ',
    'Failed to resume: ': '恢复失败: ',
    'Stopped successfully': '已成功停止',
    'Manually updating stats...': '正在手动更新统计...',
    'Update failed: ': '更新失败: ',
    'restored from server': '已从服务器恢复',
    'Close Rustatio?': '确定关闭 Rustatio?',
}

# 第二遍补漏:跨行文本节点、三元表达式标签等
TEXTS.update({
    'Watch folder instance': '监视文件夹实例',
    'Open in Watch': '在监视中打开',
    'API Token': 'API 令牌',
    'This is the': '这是服务器上设置的',
    'environment variable set on the server.': '环境变量。',
    'Remember this token': '记住此令牌',
    'Application Logs': '应用日志',
    'Clear': '清除',
    'CORS Proxy (Optional)': 'CORS 代理(可选)',
    'Solution 1 (Recommended):': '方案 1(推荐):',
    'Use the': '使用',
    'desktop app': '桌面应用',
    'Deploy a free Cloudflare Worker as a CORS proxy. See our': '部署免费的 Cloudflare Worker 作为 CORS 代理,参见',
    'setup guide': '配置指南',
    'for step-by-step instructions (takes 5 minutes).': '获取分步说明(约 5 分钟)。',
    'Proxy URL (leave empty to disable)': '代理 URL(留空禁用)',
    'Save Proxy': '保存代理',
    'Torrent File': '种子文件',
    'Change': '更换',
    'Info Hash': 'Info 哈希',
    'Primary': '主 Tracker',
    'Progressive rate adjustment': '渐变速率调整',
    'Randomize rates for realistic behavior': '随机化速率以贴近真实行为',
    'Stop Conditions': '停止条件',
    'Randomize ratio for realistic behavior': '随机化比率以贴近真实行为',
    'Range': '范围',
    'Idle when no leechers': '无下载者时空闲',
    'Idle when no seeders': '无做种者时空闲',
    'Continue (idle)': '继续(空闲)',
    'Loading...': '加载中...',
    'Empty directory': '空目录',
    'Edit Selected': '编辑选中',
    'Loading selected instance configs...': '正在加载选中实例配置...',
    'Transfer Rates': '传输速率',
    'Initial State': '初始状态',
    'Timing': '时间设置',
    'Tracker': 'Tracker',
    'Local Computer': '本地电脑',
    'Server Folder': '服务器文件夹',
    'None (manual config)': '无(手动配置)',
    'Seed (100% complete)': '做种(完成度 100%)',
    'Leech (0% complete)': '下载(完成度 0%)',
    'VPN sync is disabled on the server. Uncheck it or enable': '服务器已禁用 VPN 同步。取消勾选或启用',
    'and restart Rustatio.': '并重启 Rustatio。',
    'VPN sync is disabled on the server. Set': '服务器已禁用 VPN 同步。设置',
    'Retry': '重试',
    'Waiting for a forwarded port from Gluetun. Make sure': '正在等待 Gluetun 的转发端口。请确认',
    'is enabled and the VPN provider supports it.': '已启用且 VPN 服务商支持端口转发。',
    'Current forwarded port:': '当前转发端口:',
    'Tags (comma-separated)': '标签(逗号分隔)',
    'Stagger (sec)': '错峰间隔(秒)',
    'No instances found. Import torrents to get started.': '未找到实例。导入种子以开始。',
    'Import torrents or adjust filters to see instances here.': '导入种子或调整筛选以在此查看实例。',
    'General': '常规',
    'Presets': '预设',
    'Detection Tips': '检测提示',
    'Error:': '错误:',
    'Only critical errors': '仅关键错误',
    'Warning:': '警告:',
    'Errors and warnings': '错误与警告',
    'Info:': '信息:',
    'General information (default)': '一般信息(默认)',
    'Debug:': '调试:',
    'Detailed debugging information': '详细调试信息',
    'Trace:': '跟踪:',
    'Very verbose, includes all internal operations': '非常详细,包含全部内部操作',
    'Note: Log level changes apply to the backend.': '注意:日志级别更改对后端生效。',
    'Show a prompt to choose action': '显示提示以选择操作',
    'Keep app running in background': '应用保持在后台运行',
    'Completely close the application': '完全关闭应用',
    'Default used for watch-folder imports:': '监视文件夹导入使用的默认值:',
    'Built-in Presets': '内置预设',
    'Recommended': '推荐',
    'Applied': '已应用',
    'Custom Presets': '自定义预设',
    'Export Config': '导出配置',
    'Import Preset': '导入预设',
    'Preset Name': '预设名称',
    'Description': '描述',
    'Cancel': '取消',
    'Save': '保存',
    'Save and Set Default': '保存并设为默认',
    'Export': '导出',
    'Progress': '进度',
    'Performance': '性能',
    'Reset': '重置',
    'Elapsed': '已用时长',
    'Peers': 'Peer 数',
    'connected': '个已连接',
    'Session Stats': '会话统计',
    'Avg Upload': '平均上传',
    'Avg Download': '平均下载',
    'Session Ratio': '会话比率',
    'Total Stats': '总计统计',
    'Connected Peers': '已连接 Peer',
    'Pending': '待处理',
    'Invalid': '无效',
    'Total': '总计',
    'Watch folder is available in server and desktop modes.': '监视文件夹在服务器与桌面模式下可用。',
    'for unlimited depth.': '表示不限深度。',
    'Auto start on application startup and torrent load': '应用启动及种子加载时自动开始',
    'Active path:': '当前路径:',
    'Preset selected:': '已选预设:',
    'Filter': '筛选',
    'No files match current filters.': '没有文件符合当前筛选条件。',
    'Waiting for data...': '等待数据...',
})

ATTRS.update({
    'This instance is managed by watch folder': '此实例由监视文件夹管理',
    'Open this torrent in watch explorer': '在监视浏览器中打开此种子',
    'Settings': '设置',
    'Start': '开始',
    'Pause': '暂停',
    'Resume': '恢复',
    'Update': '更新',
    'Delete Instance': '删除实例',
})


def main():
    root = pathlib.Path('ui/src')
    changed = []
    for f in list(root.rglob('*.svelte')) + list((root / 'lib').rglob('*.js')):
        s = io.open(f, encoding='utf-8').read()
        orig = s
        for en, zh in TEXTS.items():
            s = re.sub(rf'>\s*{re.escape(en)}\s*<', f'>{zh}<', s)
        for en, zh in ATTRS.items():
            s = re.sub(
                rf'((?:\btitle|\blabel|\bplaceholder|\btooltip|\balt|\bdescription|\btext)="){re.escape(en)}(")',
                lambda m: m.group(1) + zh + m.group(2),
                s,
            )
        for en, zh in MSG.items():
            s = s.replace(f"'{en}'", f"'{zh}'").replace(f'"{en}"', f'"{zh}"')
        s = s.replace('Instance ${instance.id}', '实例 ${instance.id}')
        if s != orig:
            io.open(f, 'w', encoding='utf-8', newline='\n').write(s)
            changed.append(str(f))
    print(f'修改了 {len(changed)} 个文件')
    for c in changed:
        print(' -', c)


if __name__ == '__main__':
    main()
